#!/usr/bin/env python

import sys
import csv

r = csv.reader(open(sys.argv[1], "rb"))

headers = list(enumerate(r.next()))

params = []
for i in sys.argv[2:]:
    t = i.split("=")

    k = t[0]
    if len(t) == 1:
        e = None
    else:
        e = t[1]

    params.append((k, e))

cols = []

values = []
for i in params:
    s = i[0].lower()
    for n, name in headers:
        if s in name.lower():
            cols.append((n, i[1]))
            values.append(headers[n][1])

if not cols:
    print 'You must specify some columns to show, or search against.'
    sys.exit(1)

print "\t".join(values)

for i in r:
    values = []
    terms = 0
    found = 0

    for n, e in cols:
        v = i[n]
        if e != None:
            terms += 1
            if e.lower() in v.lower():
                found += 1

        values.append(v)

    if terms == found:
        print "\t".join(values)
